GET http://localhost:8080/
###
POST  http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Test",
  "coockingTime": 30,
  "ingredients": [
    {"title": "TestIngredient",
      "number": "1",
      "measure": "piece"
    }
  ],
  "steps": [
    "Step1",
    "Step2"
  ]
}